# Generated by Django 3.0.4 on 2020-04-18 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20200418_1217'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price_sale',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
