# Generated by Django 3.0.4 on 2020-04-19 08:25

from django.db import migrations, models
import shop.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_product_price_sale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price_sale',
            field=models.DecimalField(decimal_places=2, default=shop.models.Product.set_discount, max_digits=10),
        ),
    ]
