# Generated by Django 3.0.4 on 2020-04-20 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20200419_0825'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price_sale',
        ),
    ]
