
# Generated by Django 3.0.4 on 2020-04-20 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_auto_20200420_1521'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('date', models.DateField()),
                ('author', models.CharField(max_length=255)),
                ('icon_chat', models.PositiveIntegerField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-name']},
        ),
    ]
