# Generated by Django 3.0.4 on 2020-04-20 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_auto_20200420_1925'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='image',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
    ]
